/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidarRouteImport } from './routes/validar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdicionarRouteImport } from './routes/adicionar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceitaIdRouteImport } from './routes/receita.$id'
import { Route as ReceitaIdCozinharRouteImport } from './routes/receita.$id.cozinhar'

const ValidarRoute = ValidarRouteImport.update({
  id: '/validar',
  path: '/validar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdicionarRoute = AdicionarRouteImport.update({
  id: '/adicionar',
  path: '/adicionar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitaIdRoute = ReceitaIdRouteImport.update({
  id: '/receita/$id',
  path: '/receita/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitaIdCozinharRoute = ReceitaIdCozinharRouteImport.update({
  id: '/cozinhar',
  path: '/cozinhar',
  getParentRoute: () => ReceitaIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/login': typeof LoginRoute
  '/validar': typeof ValidarRoute
  '/receita/$id': typeof ReceitaIdRouteWithChildren
  '/receita/$id/cozinhar': typeof ReceitaIdCozinharRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/login': typeof LoginRoute
  '/validar': typeof ValidarRoute
  '/receita/$id': typeof ReceitaIdRouteWithChildren
  '/receita/$id/cozinhar': typeof ReceitaIdCozinharRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/login': typeof LoginRoute
  '/validar': typeof ValidarRoute
  '/receita/$id': typeof ReceitaIdRouteWithChildren
  '/receita/$id/cozinhar': typeof ReceitaIdCozinharRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adicionar'
    | '/login'
    | '/validar'
    | '/receita/$id'
    | '/receita/$id/cozinhar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adicionar'
    | '/login'
    | '/validar'
    | '/receita/$id'
    | '/receita/$id/cozinhar'
  id:
    | '__root__'
    | '/'
    | '/adicionar'
    | '/login'
    | '/validar'
    | '/receita/$id'
    | '/receita/$id/cozinhar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdicionarRoute: typeof AdicionarRoute
  LoginRoute: typeof LoginRoute
  ValidarRoute: typeof ValidarRoute
  ReceitaIdRoute: typeof ReceitaIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validar': {
      id: '/validar'
      path: '/validar'
      fullPath: '/validar'
      preLoaderRoute: typeof ValidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adicionar': {
      id: '/adicionar'
      path: '/adicionar'
      fullPath: '/adicionar'
      preLoaderRoute: typeof AdicionarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receita/$id': {
      id: '/receita/$id'
      path: '/receita/$id'
      fullPath: '/receita/$id'
      preLoaderRoute: typeof ReceitaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receita/$id/cozinhar': {
      id: '/receita/$id/cozinhar'
      path: '/cozinhar'
      fullPath: '/receita/$id/cozinhar'
      preLoaderRoute: typeof ReceitaIdCozinharRouteImport
      parentRoute: typeof ReceitaIdRoute
    }
  }
}

interface ReceitaIdRouteChildren {
  ReceitaIdCozinharRoute: typeof ReceitaIdCozinharRoute
}

const ReceitaIdRouteChildren: ReceitaIdRouteChildren = {
  ReceitaIdCozinharRoute: ReceitaIdCozinharRoute,
}

const ReceitaIdRouteWithChildren = ReceitaIdRoute._addFileChildren(
  ReceitaIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdicionarRoute: AdicionarRoute,
  LoginRoute: LoginRoute,
  ValidarRoute: ValidarRoute,
  ReceitaIdRoute: ReceitaIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
